services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 3306
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb-data:/var/lib/mysql

  # nginx:

  # wordpress:


networks:
  inception:
    name: inception
    driver: bridge


volumes:
  mariadb-data:
    driver_opts:
      o: bind
      type: none
      device: /home/ehay/data/db
  # wordpress: