services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
  build:
    context: ./requirements/mariadb
    dockerfile: Dockerfile
  networks:
    - inception
  expose:
    - 3306
  restart: always
  env_file:
    - path: .env
      required: true
  volumes:
    - mariadb:/var/lib/mysql

  nginx:

  wordpress:


networks:
  incecption:
    name: inception
    driver: bridge


volumes:
  mariadb-data:
    driver_opts:
      o: bind
      type: none
      device: /home/ehay/data/database
  wordpress: