services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 3306
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

  nginx:
    container_name: nginx
    hostname: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - 443:443
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html:ro

  wordpress:
    container_name: wordpress
    hostname: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    expose:
      - 9000
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html


networks:
  inception:
    name: inception
    driver: bridge


volumes:
  mariadb_data:
    driver_opts:
      o: bind
      type: none
      device: /home/ehay/data/db
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/ehay/data/wordpress